Add missing include in BufferedStreamReader
Fixes the following compilation error on gcc 11.1.0:

	/usr/bin/ccache /usr/bin/c++ ... -c /src/audacity/libraries/lib-utility/BufferedStreamReader.cpp

	In file included from /src/audacity/libraries/lib-utility/BufferedStreamReader.cpp:11:
	/src/audacity/libraries/lib-utility/BufferedStreamReader.h:25:21: error: ‘size_t’ does not name a type
	   25 |    static constexpr size_t RequiredAlignment = 8;
	      |                     ^~~~~~
	/src/audacity/libraries/lib-utility/BufferedStreamReader.h:15:1: note: ‘size_t’ is defined in header ‘<cstddef>’; did you forget to ‘#include <cstddef>’?
	   14 | #include <cstdint>
	  +++ |+#include <cstddef>
	   15 | #include <type_traits>