wxTimerEvent::wxTimerEvent() not available in wxWidgets 3.2 API
default ctor creates an unusable event object and should not be used
(in fact, no code outside wxWidgets is supposed to create event objects)
9e2ff111a4 ("Restore, but deprecate, default ctor of wxTimerEvent", 2019-10-11)

audacity-sources-3.7.5/src/TimerRecordDialog.cpp:257:17: error: no matching function for call to ‘wxTimerEvent::wxTimerEvent()’
  257 |    wxTimerEvent dummyTimerEvent;
      |