Add <wx/bitmap.h> to effect.h
I get this error when compiling with MINGW:

In file included from ../../audacity/src/effects/EffectManager.h:20:0,
                 from ../../audacity/src/AudioIO.cpp:462:
../../audacity/src/effects/Effect.h: At global scope:
../../audacity/src/effects/Effect.h:670:13: error: field 'mPlayBM' has incomplet
e type 'wxBitmap'

This error does not happen when building with CYGWIN.
The two compilers use identical wxWidgets include files, except that MINGW includes MSW files while CYGWIN includes the GTK ones.
Probably, "wx/bitmap.h" is internally included by some files of the unix ports, while it is not the same for Windows.
Since effect.h explicitely uses wxBitmap object, perhaps it would be worth to include this files.