[CMAKE] Portaudio: fix support in Cygwin (#438)
* [CMAKE] Portaudio: add unix paths for Cygwin

When building on Cygwin, I got this error:

/home/carlo/audacity/lib-src/portaudio-v19/src/hostapi/oss/pa_unix_oss.c:90:10: fatal error: pa_unix_util.h: No such file or directory
   90 | #include "pa_unix_util.h"

this happened because some additional search path was not included.

* [CMAKE] Portaudio: add missing Unix files in Cygwin

When doing the final link of Audacity executable on Cygwin, many errors like this one were printed on the console.

/usr/lib/gcc/x86_64-pc-cygwin/9.2.0/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/Audacity.dir/AudioIO.cpp.o:AudioIO.cpp:(.text+0x17a): undefined reference to `PaUtil_GetTime'

This happened because some files were missing since Cygwin name was not included together with other unix platforms.