Add wx/evtloop.h for WXMSW
I got this error when compiling with MINGW:

../../audacity/src/CrashReport.cpp: In function 'void CrashReport::Generate(wxDebugReport::Context)':
../../audacity/src/CrashReport.cpp:56:17: error: incomplete type 'wxEventLoop' used in nested name specifier

Actually, the usage of wxEventLoop is conditioned only for WXMSW platform, so it has been added here.