[CMAKE] Portaudio: add missing Unix files in Cygwin
When doing the final link of Audacity executable on Cygwin, many errors like this one were printed on the console.

/usr/lib/gcc/x86_64-pc-cygwin/9.2.0/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/Audacity.dir/AudioIO.cpp.o:AudioIO.cpp:(.text+0x17a): undefined reference to `PaUtil_GetTime'

This happened because some files were missing since Cygwin name was not included together with other unix platforms.