[CMAKE] Portaudio: add unix paths for Cygwin
When building on Cygwin, I got this error:

/home/carlo/audacity/lib-src/portaudio-v19/src/hostapi/oss/pa_unix_oss.c:90:10: fatal error: pa_unix_util.h: No such file or directory
   90 | #include "pa_unix_util.h"

this happened because some additional search path was not included.