Fix linking of libsuil
libsuil uses directly symbols of X11 when compiling with GTK2. The build
will fail if compiled with -Wl,--as-needed:

[6/6] cshlib: build/src/x11_in_gtk2.c.3.o -> build/libsuil_x11_in_gtk2.so
src/x11_in_gtk2.c.3.o: In function `forward_key_event':
lib-src/lv2/suil/build/../src/x11_in_gtk2.c:159: undefined reference to `XSendEvent'
src/x11_in_gtk2.c.3.o: In function `x_window_is_valid':
lv2/suil/build/../src/x11_in_gtk2.c:71: undefined reference to `XQueryTree'
src/x11_in_gtk2.c.3.o: In function `forward_size_request':
lib-src/lv2/suil/build/../src/x11_in_gtk2.c:172: undefined reference to `XResizeWindow'
collect2: error: ld returned 1 exit status
Waf: Leaving directory `lib-src/lv2/suil/build'
Build failed

Therefore link against X11 when using GTK2.