Add missing include in XMLAttributeValueView.cpp
Fixes the following compilation error on gcc 11.1.0:

	/usr/bin/ccache /usr/bin/c++ ... -c /src/audacity/libraries/lib-xml/XMLAttributeValueView.cpp
	/src/audacity/libraries/lib-xml/XMLAttributeValueView.cpp: In function ‘bool CheckInteger(ResultType&, int64_t)’:
	/src/audacity/libraries/lib-xml/XMLAttributeValueView.cpp:290:38: error: ‘numeric_limits’ is not a member of ‘std’
	  290 |    constexpr int64_t minValue = std::numeric_limits<ResultType>::min();
	      |                                      ^~~~~~~~~~~~~~