New configs now really 64 bit; they compile, almost link...
... The null, script-pipe, and Nyquist workbench modules all build fully.

Just two missing symbols building Audacity, I don't yet know why:

ld: warning: directory not found for option '-L/Users/paullicameli/GitHub/audacity/mac/build/Release'
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks//QuickTime.framework/QuickTime, file was built for i386 which is not the architecture being linked (x86_64): /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks//QuickTime.framework/QuickTime
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ModalDialogDelegate", referenced from:
      objc-class-ref in FileDialogPrivate.o
  "_objc_readClassPair", referenced from:
      __ARCLite__load() in libarclite_macosx.a(arclite.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)