Possible MSVC buildbot fix.
The buildbot was reporting "error C2440: 'default argument' : cannot convert from 'initializer-list' to 'const wxString &'" for prefs.h