[CORE] Fix build: images/Cursors.h not found
Similar to #3120, I got this error when compiling Audacity:

/home/Carlo/audacity/src/tracks/playabletrack/wavetrack/ui/WaveClipTrimHandle.cpp:19:10: fatal error: ../../../images/Cursors.h: No such file or directory
   19 | #include "../../../images/Cursors.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~

Actually, it is needed to rise more levels for reaching the point where images/Cursors.h is stored.
I think that there are no more issue like this one because it is possible to reach the link command after this fix.