Add missing #include <algorithm> to WaveChannelViewConstants
For std::sort() and std::adjacent_find()

audacity-sources-3.7.5/libraries/lib-wave-track/WaveChannelViewConstants.cpp:64:18: error: ‘sort’ is not a member of ‘std’; did you mean ‘qsort’?
   64 |             std::sort( begin, end );
      |                  ^~~~
      |                  qsort

audacity-sources-3.7.5/libraries/lib-wave-track/WaveChannelViewConstants.cpp:66:35: error: ‘adjacent_find’ is not a member of ‘std’
   66 |             wxASSERT( end == std::adjacent_find( begin, end ) );
      |                                   ^~~~~~~~~~~~~