[CMAKE] Portmidi: add missing Unix files in Cygwin
When doing the final link of Audacity executable on Cygwin, many errors like this one were printed on the console:

ld: ../lib/audacity/libportmidi.a(portmidi.c.o):portmidi.c:(.text+0x3f): undefined reference to `pm_alloc'

This happened because some files were missing since Cygwin name was not included together with other unix platforms.